### ISSUE TITLE
SyntaxError: invalid syntax - def gen_rand_str(*size, use=None, keyspace=None):

### ISSUE THREAD

**Issue by fredfalcon** [jaredlunde/vital-tools#1]
```
Collecting vital-tools
  Using cached vital-tools-0.1.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-h4h1zV/vital-tools/setup.py", line 51, in <module>
        packages=list(find_packages(PKG))
      File "/tmp/pip-build-h4h1zV/vital-tools/setup.py", line 34, in find_packages
        for _, name, ispkg in walk_packages(path, prefix):
      File "/usr/lib/python2.7/pkgutil.py", line 110, in walk_packages
        __import__(name)
      File "vital/debug/__init__.py", line 338
        def gen_rand_str(*size, use=None, keyspace=None):
                                  ^
    SyntaxError: invalid syntax

```

**Comment by Bluesands** [comment]
I also met the same problem when I pip install the redis-cache

**Comment by jaredLunde** [comment]
Hi there,

Sorry for the late reply, but both redis-cache and vital-tools are Python 3+ only. There is no roadmap toward reaching 2.7 compatibility as the overwhelming majority of popular Python libraries are now 3.4+ compatible (https://python3wos.appspot.com/).

I understand the majority of applications being written are still utilizing 2.7, but I can't justify spending the time when the EOL is in 2020. It also hampers the ability to incorporate critical 3.4+ features like asyncio.

Apologies for any inconvenience! I hope you found a library which better suited you.

**Comment by fredfalcon** [comment]
Thanks, I got around the issue by removing it from the requirements file and using django-redis-cache instead.
